CREATE DATABASE hr_department;

CREATE TABLE `hr_database`.`regions` (
	`REGION_ID` INT(10) NOT NULL , 
	 `REGION_NAME` TEXT NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `regions` ADD PRIMARY KEY(`REGION_ID`);

CREATE TABLE `hr_database`.`countries` (
	`COUNTRY_ID` INT(7) NOT NULL , 
	`COUNTRY_NAME` TEXT NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `countries` ADD PRIMARY KEY(`COUNTRY_ID`);

CREATE TABLE `hr_database`.`locations` (`LOCATION_ID` INT(5) NOT NULL , 
	`PROVINCE` VARCHAR(256) NOT NULL , 
	`CITY` VARCHAR(256) NOT NULL , 
	`ZIP_CODE` INT(4) NOT NULL , 
	`STREET_ADDRESS` VARCHAR(256) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `locations` ADD PRIMARY KEY(`LOCATION_ID`);

CREATE TABLE `hr_database`.`departments` (`DEPARTMENT_ID` INT(5) NOT NULL , 
	`DEPARTMENT_NAME` VARCHAR(256) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `departments` ADD PRIMARY KEY(`DEPARTMENT_ID`);

CREATE TABLE `hr_database`.`employees` (`EMPLOYEE_ID` INT(8) NOT NULL , 
	`FIRST_NAME` VARCHAR(256) NOT NULL , 
	`LAST_NAME` VARCHAR(256) NOT NULL , 
	`EMAIL` VARCHAR(256) NOT NULL , 
	`PHONE_NUMBER` INT(11) NOT NULL , 
	`HIRE_DATE` VARCHAR(20) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `employees` ADD PRIMARY KEY(`EMPLOYEE_ID`);

CREATE TABLE `hr_database`.`jobs` (`JOB_ID` INT(6) NOT NULL , 
	`JOB_TITLE` VARCHAR(256) NOT NULL , 
	`SALARY` VARCHAR(15) NOT NULL , 
	`MIN.SALARY` VARCHAR(15) NOT NULL , 
	`MAX.SALARY` VARCHAR(15) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `jobs` ADD PRIMARY KEY(`JOB_ID`);

CREATE TABLE job_history(
    'EMPLOYEE_ID' INT(
   	FOREIGN KEY(EMPLOYEE_ID)REFERENCES employees(EMPLOYEE_ID) ON DELETE NO ACTION,
    FOREIGN KEY(JOB_ID) REFERENCES jobs(JOB_ID) ON DELETE NO ACTION,
    'START_DATE' VARCHAR(255),
    'END_DATE' VARCHAR(255)
    );

CREATE TABLE job_grades( 
	'JOB_ID' INT(6), FOREIGN KEY(JOB_ID) REFERENCES jobs(JOB_ID) ON DELETE NO ACTION, 
	'GRADE_LEVEL' VARCHAR(255), 
	'LOWEST_SAL' VARCHAR(255), 
	'HIGHEST_SAL' VARCHAR(255) 
	);



INSERT INTO `employees` (`EMPLOYEE_ID`, `FIRST_NAME`, `LAST_NAME`, `EMAIL`, `PHONE_NUMBER`, `HIRE_DATE`) 
VALUES 
	('10223455', 'Yzer Vincent', 'De Omania', 'yzervincent@gmail.com', '331951324', 'October 20, 2021'),
	('12312512', 'John', 'Cena', 'cena@gmail.com', '331851251', 'January 5, 2012'),
	('12355122', 'Robinx\r\n', 'Aquino', 'aquino@gmail.com', '312312317', 'September 12, 2016');

INSERT INTO `departments` (`DEPARTMENT_ID`, `DEPARTMENT_NAME`) 
VALUES 
    ('12313', 'MANAGEMENT INFORMATION SYSTEM\r\n'), 
	('44123', 'FINANCE MANAGEMENT'), 
	('61234', 'SALES DEPARTMENT'), 
	('66234', 'HR DEPARTMENT'), 
	('51616', 'MARKETING DEPARTMENT'), 
	('51123', 'ACCOUNTING '), 
	('76234', 'SECURITY DEPARTMENT'), 
	('87672', 'RESEARCH AND DEVELOPMENT'), 
	('61341', 'SUPPORT AND SERVICES '), 
	('23151', 'OPERATIONS DEPARTMENT');

INSERT INTO `countries` (`COUNTRY_ID`, `COUNTRY_NAME`) 
VALUES 
('5552123', 'PHILIPPINES'), 
('5123151', 'TAIWAN'), 
('1231251', 'JAPAN'), 
('5687431', 'INDONESIA'), 
('9755323', 'SINGAPORE');

INSERT INTO `regions` (`REGION_ID`, `REGION_NAME`) 
VALUES ('12342659', 'REGION III - CENTRAL LUZON'), 
('532423421', 'REGION  IV B - MIMAROPA');


INSERT INTO `locations` (`LOCATION_ID`, `PROVINCE`, `CITY`, `ZIP_CODE`, `STREET_ADDRESS`) 
VALUES ('95731', 'Tampines', 'Simei City', '0923', '277 Orchard Road'), 
('64342', 'Zambales', 'Olongapo City', '2200', 'Ariola st. Gordon Heights');

INSERT INTO `jobs` (`JOB_ID`, `JOB_TITLE`, `SALARY`, `MIN.SALARY`, `MAX.SALARY`) 
VALUES ('412465', 'Network Analyst', '94,500php', '90,000php', '100,100php'), 
('123151', 'Sales Admin Executive ', '35,000php', '33,200php', '36,000php');

INSERT INTO `job_grades` (`JOB_ID`, `GRADE_LEVEL`, `LOWEST_SAL`, `HIGHEST_SAL`) 
VALUES ('412465', 'GRADE 24', '90,078php', '100,888php'), 
('123151', 'GRADE 14', '33,843php', '36,341php');

INSERT INTO `job_history` (`EMPLOYEE_ID`, `JOB_ID`, `START_DATE`, `END_DATE`) 
VALUES ('10223455', '412465', 'November 15, 2021', 'September 21, 2024'), 
('12355122', '123151', 'September 30, 2016', 'December 10, 2020');